language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
matrix:
  include:
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx-image: xcode11
      language: shell
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      script:
        - alias python3=python
        - ./test
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
  allow_failures:
    - os: windows
install: pip3 install --upgrade pip
script: ./test
