version: 0.3.0 build {build}-{branch}
branches:
  only:
    - master
    - develop
environment:
  matrix:
    - PYTHON: "C:\\Python34\\python.exe"
    - PYTHON: "C:\\Python34-x64\\python.exe"
    - PYTHON: "C:\\Python35\\python.exe"
    - PYTHON: "C:\\Python35-x64\\python.exe"
    - PYTHON: "C:\\Python36\\python.exe"
    - PYTHON: "C:\\Python36-x64\\python.exe"
    - PYTHON: "C:\\Python37\\python.exe"
    - PYTHON: "C:\\Python37-x64\\python.exe"
platform:
  - x64
  - x86
build: off
init: ECHO %PYTHON%
before_test:
  - doskey python3="%PYTHON%"
  - python3 --version
test_script:
  - bash test
