version: 0.3.0 build {build}-{branch}
branches:
  only:
    - master
    - develop
environment:
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
platform:
  - x64
  - x86
build: off
init: ECHO %PYTHON%
before_test:
  - doskey python3=%PYTHON%\\python.exe %*
  - python3 --version
test_script:
  - bash test